name: main_workflow
on: 
 push: 
  branches:
   - githubActions_improvement
jobs:
  syntax_check_job:
    name: syntax_check_job
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: LinterExecution
       uses: github/super-linter@v3
       env:
          DEFAULT_BRANCH: githubActions_improvement
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
          VALIDATE_JAVASCRIPT_ES: true
  
  test_execution_job:
    name: test_execution_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Ejecutar tests
        run: |
          npm i
          npm run test
  
  build_statics_job:
    name: build_statics_job
    runs-on: ubuntu-latest
    needs: [syntax_check_job, test_execution_job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm i
          npm run buildDev
      - name: artifact upload
        uses: actions/upload-artifact@v2
        with: 
          name: build
          path: ./dist